#!/bin/sh
# 
# build
# 
# Builds API documentation for Cedar using apigen
# @author Dean Inglis <inglisd@mcmaster.ca>

# get the path to cedar
cedar_path=`grep "\['path'\]\['CEDAR'\]" ../web/settings.local.ini.php | sed -e "s#.* = '\(.*\)';#\1#"`

# generate the documentation
apigen --source "$cedar_path/api,../api" --config apigen.conf
