<?php
/**
 * settings.ini.php
 * 
 * Defines initialization settings for cedar.
 * DO NOT edit this file, to override these settings use settings.local.ini.php instead.
 * Any changes in the local ini file will override the settings found here.
 */

global $SETTINGS;

// tagged version
$SETTINGS['general']['application_name'] = 'cedar';
$SETTINGS['general']['service_name'] = $SETTINGS['general']['application_name'];
$SETTINGS['general']['version'] = '0.1.3';

// always leave as false when running as production server
$SETTINGS['general']['development_mode'] = false;

// defines the username and password used by cedar when communicating as a machine
$SETTINGS['general']['machine_user'] = NULL;
$SETTINGS['general']['machine_password'] = NULL;

// the name of the cohort associated with this application
$SETTINGS['general']['cohort'] = 'default';

// the default number of classification test entry inputs
$SETTINGS['interface']['classification_max_rank'] = 40;

// the url of sabretooth (set to NULL to disable sabretooth support)
$SETTINGS['url']['SABRETOOTH'] = NULL;

// the location of cedar internal path
$SETTINGS['path']['APPLICATION'] = '/usr/local/lib/cedar';
