<?php
/**
 * settings.ini.php
 * 
 * Defines initialization settings for cedar.
 * DO NOT edit this file, to override these settings use settings.local.ini.php instead.
 * Any changes in the local ini file will override the settings found here.
 */

global $SETTINGS;

// tagged version
$SETTINGS['general']['application_name'] = 'cedar';
$SETTINGS['general']['service_name'] = $SETTINGS['general']['application_name'];
$SETTINGS['general']['version'] = '0.1.1';

// always leave as false when running as production server
$SETTINGS['general']['development_mode'] = false;

// the name of the cohort associated with this application
$SETTINGS['general']['cohort'] = 'default';

// the location of cedar internal path
$SETTINGS['path']['APPLICATION'] = '/usr/local/lib/cedar';
